weights: ./models/st_gcn.tp-imu.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/TotalCapture/vicon/val_data.npy
  label_path: ./data/TotalCapture/vicon/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'tp-vicon'
    strategy: 'spatial'

# test 
phase: test
device: 0
test_batch_size: 64

