work_dir: ./work_dir/recognition/tp-imu/ST_GCN

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ./data/TotalCapture/imu/train_data.npy
  label_path: ./data/TotalCapture/imu/train_label.pkl
test_feeder_args:
  data_path: ./data/TotalCapture/imu/val_data.npy
  label_path: ./data/TotalCapture/imu/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 7
  num_class: 4
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'tp-imu'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [20,30,50]

# training
device: [0,1]
batch_size: 64
test_batch_size: 64
num_epoch: 80



