weights: ./models/st_gcn.congreg8-marker.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/CongreG8/marker/val_data.npy
  label_path: ./data/CongreG8/marker/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'congreg8-marker'
    strategy: 'spatial'

# test 
phase: test
device: 0
test_batch_size: 64

